#!/bin/sh
set -e
if [ "$1" = "configure" ]; then
	mkdir -p /var/lib/hubabox
	if command -v systemctl >/dev/null 2>&1; then
		systemctl daemon-reload
		systemctl enable hubabox.service
		systemctl restart hubabox.service
	fi
fi
exit 0
