#!/bin/sh
set -e
if [ "$1" = "remove" ] || [ "$1" = "deconfigure" ]; then
	if command -v systemctl >/dev/null 2>&1; then
		systemctl stop hubabox.service || true
		systemctl disable hubabox.service || true
	fi
fi
exit 0
